# Generated by Django 3.1.7 on 2021-09-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
