# Generated by Django 3.1.7 on 2021-04-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.TextField(max_length=50)),
                ('album', models.TextField(max_length=50)),
                ('title', models.TextField(max_length=50)),
                ('track_num', models.IntegerField()),
                ('genre', models.TextField(max_length=50)),
                ('recording_date', models.IntegerField()),
                ('cover', models.URLField(max_length=255)),
                ('path', models.URLField(max_length=255)),
            ],
        ),
    ]
