# Generated by Django 3.1.7 on 2022-04-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('rec_date', models.DateField()),
                ('album_art', models.ImageField(null=True, upload_to='uploads/<django.db.models.fields.related.ForeignKey>/title')),
                ('number_of_tracks', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Artist', max_length=100)),
                ('picture', models.ImageField(null=True, upload_to='uploads/<django.db.models.fields.CharField>')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('duration', models.IntegerField(default=0)),
                ('track_number', models.IntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.albums')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artists')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.AddField(
            model_name='albums',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artists'),
        ),
    ]
