# Generated by Django 3.1.7 on 2021-04-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210425_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='cover',
        ),
    ]
