# Generated by Django 3.1.7 on 2022-05-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220504_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albums',
            name='number_of_tracks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
