# Generated by Django 3.1.7 on 2021-04-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210426_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='cover',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
