# Generated by Django 3.1.7 on 2022-05-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220504_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='albums',
            name='number_of_tracks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
