# Generated by Django 3.1.7 on 2022-05-11 14:41

from django.db import migrations, models
import main.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220510_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='file',
            field=models.FileField(storage=main.custom_storage.MyFileStorage(), upload_to=''),
        ),
    ]
