# Generated by Django 3.1.7 on 2021-09-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210901_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='album',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='recording_date',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='track_num',
        ),
    ]
