# Generated by Django 3.1.7 on 2021-09-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210904_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='path',
            field=models.FilePathField(path='/home/stas/PycharmProjects/mp3_module/2009_-_Crack_The_Skye/CD_1/'),
        ),
    ]
