# Generated by Django 3.1.7 on 2021-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210904_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('path', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Sound',
                'verbose_name_plural': 'Sounds',
            },
        ),
    ]
