# Generated by Django 3.1.7 on 2022-05-15 20:05

from django.db import migrations, models
import main.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220515_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='file',
            field=models.FileField(storage=main.custom_storage.MyFileStorage(), upload_to=''),
        ),
    ]
