# Generated by Django 3.1.7 on 2022-05-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220515_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='duration',
        ),
    ]
