# Generated by Django 3.1.7 on 2022-01-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sounds',
            name='artist',
            field=models.TextField(default='Untitled Artist', max_length=50),
        ),
    ]
