# Generated by Django 3.1.7 on 2022-05-15 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_albums_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='number_of_tracks',
        ),
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='main.albums'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='main.artists'),
        ),
    ]
